
install: ## install deps
	@pnpm install
.PHONY: install

deploy: ## deploy worker
	@pnpm run deploy
.PHONY: deploy

dev: ## run dev server
	@pnpm run dev
.PHONY: dev

types:
	@pnpm run cf-typegen
.PHONY: types

