# Generated by Django 5.1.7 on 2025-03-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="title",
            field=models.CharField(),
        ),
    ]
