# Generated by Django 5.1.7 on 2025-03-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0002_alter_application_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationstatus",
            name="name",
            field=models.CharField(),
        ),
    ]
