# Generated by Django 5.1.7 on 2025-03-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0004_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="document_path",
            field=models.CharField(default="test"),
            preserve_default=False,
        ),
    ]
