# Generated by Django 5.1.7 on 2025-03-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0005_prompt_document_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prompt",
            old_name="document_path",
            new_name="name",
        ),
    ]
