# Generated by Django 5.1.7 on 2025-03-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0006_rename_document_path_prompt_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
