# Generated by Django 5.1.7 on 2025-03-18 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0007_prompt_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompts",
                to="job_applications.application",
            ),
        ),
    ]
