# Generated by Django 5.1.7 on 2025-03-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0008_alter_prompt_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="company",
            field=models.CharField(default=""),
        ),
    ]
