# Generated by Django 5.1.7 on 2025-03-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0009_application_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="resume",
        ),
    ]
