# Generated by Django 5.1.7 on 2025-03-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0010_remove_application_resume"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="url",
            new_name="job_url",
        ),
        migrations.AddField(
            model_name="application",
            name="resume_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
