# Generated by Django 5.1.7 on 2025-03-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0012_alter_application_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prompt",
            options={"ordering": ["-id"]},
        ),
    ]
