# Generated by Django 5.1.7 on 2025-03-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0015_application_resume_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="formatting_template",
            field=models.CharField(blank=True, null=True),
        ),
    ]
