# Generated by Django 5.1.7 on 2025-03-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0016_prompt_formatting_template"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prompt",
            old_name="formatting_template",
            new_name="formatting_response_template",
        ),
    ]
