# Generated by Django 5.1.7 on 2025-03-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_applications",
            "0017_rename_formatting_template_prompt_formatting_response_template",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="formatting_description_template",
            field=models.CharField(blank=True, null=True),
        ),
    ]
