# Generated by Django 5.1.7 on 2025-03-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0018_prompt_formatting_description_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="resume_replace_path",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="formatting_description_template",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="formatting_response_template",
            field=models.TextField(blank=True, null=True),
        ),
    ]
