# Generated by Django 5.1.7 on 2025-04-15 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_applications",
            "0020_remove_prompt_formatting_description_template_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="job_applications.applicationstatus",
            ),
        ),
    ]
