# Generated by Django 5.1.7 on 2025-05-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0022_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
