# Generated by Django 5.1.7 on 2025-05-20 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0023_application_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='JobURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_applications.urlstatus')),
            ],
        ),
    ]
