# Generated by Django 5.1.7 on 2025-07-11 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0024_urlstatus_joburl'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='job_applications.prompt'),
        ),
    ]
