# Generated by Django 5.1.7 on 2025-07-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0025_prompt_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='include_databricks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='include_project_management',
            field=models.BooleanField(default=True),
        ),
    ]
