# Generated by Django 5.1.7 on 2025-08-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0026_application_include_databricks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
