# Generated by Django 5.1.7 on 2025-08-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0027_prompt_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, default="## 1st interview Questions\n\n- How many steps are there?\n- How many people are ahead of me and what's the furthest step they're at?\n- What's the salary range?\n- What about my resume interested you for this role?\n- How hungry are you for this role?\n", null=True),
        ),
    ]
