# Generated by Django 5.1.7 on 2026-02-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0028_alter_application_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_scanned_browserless',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_scanned_requests',
            field=models.DateTimeField(null=True),
        ),
    ]
